In [2]:
import csv
with open("data.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name", "Age", "City"])
    writer.writerow(["Prasi", "20", "Kakinada"])
    writer.writerow(["Sai", "21", "Hyderabad"])

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])

In [5]:
print(a.ndim)

1


In [6]:
b=np.array([[1,2,3],[4,5,6]])

In [7]:
print(b.ndim)

2


In [8]:
c = np.array([[[1,2],[3,4],[5,6],[7,6]]])

In [9]:
print(c.ndim)

3


In [10]:
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 6]]]


In [11]:
print(a.shape)

(4,)


In [12]:
print(b.shape)

(2, 3)


In [13]:
print(c.shape)

(1, 4, 2)


# FUNCTIONS FOR CREATING ARRAY

In [14]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


# Using linspace

In [16]:
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [17]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
print(np.diag(a))

[1 2 3 4]


# Basic Data Types

In [22]:
a = np.arange(10)
print(a.dtype)

int64


In [23]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [24]:
a = np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other Data Types

In [25]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [26]:
a = np.array([True,False])
print(a.dtype)

bool


In [27]:
a = np.array(['pavan','mani'])
print(a.dtype) #Unicode string type

<U5


# Indexing and slicing

In [28]:
a = np.arange(10)
print(a[5])

5


In [29]:
a = np.diag([1,2,3])
print(a[2,2])

3


# Slicing

In [30]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(a[1:8:2])

[1 3 5 7]


In [33]:
a = np.arange(10)
a[5: ]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# Copies and viewing

In [34]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [35]:
print(np.shares_memory(a,b))

True


In [36]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [37]:
a = np.arange(10)
b = a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [38]:
print(np.shares_memory(a,b))

False


In [39]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random number generator

In [41]:
a = np.random.randint(0,20,15)
print(a)

[ 6  4 11  5  6 13  5  0  0  2  3  4  9 15  4]


In [42]:
mask=(a%2==0)

In [43]:
mask_a = a[mask]
print(mask_a)

[6 4 6 0 0 2 4 4]


In [44]:
a[mask] = -1
print(a)

[-1 -1 11  5 -1 13  5 -1 -1 -1  3 -1  9 15 -1]


# Element wise Operation

1.Basic Opeartion

In [45]:
a = np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [46]:
print(a**2)

[ 1  4  9 16]


# All Arthimetic Operates Element Wise

In [47]:
b = np.ones(4) + 1
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [48]:
print(a*b)

[2. 4. 6. 8.]


In [49]:
print(a+b)

[3. 4. 5. 6.]


In [50]:
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [51]:
print(c*c)
print("************************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision Operators

In [52]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [53]:
print(np.array_equal(a,c))

True


# logical Operators

In [54]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,1,0,0],dtype = "bool")

In [55]:
print(np.logical_or(a,b))

[ True  True  True False]


In [57]:
print(np.logical_and(a,b))

[ True False False False]


# Trigonometry/Transcendental Function

In [58]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [59]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [60]:
np.log(a)

C:\Users\PRASANNA\AppData\Local\Temp\ipykernel_8084\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])